# Generated by Django 2.2.9 on 2019-12-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('Telefone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Nascimento', models.DateField()),
                ('Radiação', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
