# Generated by Django 2.0.1 on 2018-02-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('Radiação', models.IntegerField()),
            ],
        ),
    ]
