# Generated by Django 2.2.6 on 2019-11-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Name',
            new_name='Nome',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Radiação',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
